apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopnow-backend
  template:
    metadata:
      labels:
        app: shopnow-backend
    spec:
      containers:
      - name: backend
        image: kumarDevOps/shopnow-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: shopnow-backend-service
spec:
  selector:
    app: shopnow-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
