apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopnow-frontend
  template:
    metadata:
      labels:
        app: shopnow-frontend
    spec:
      containers:
      - name: frontend
        image: kumarDevOps/shopnow-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shopnow-frontend-service
spec:
  selector:
    app: shopnow-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
