apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopnow-frontend
  template:
    metadata:
      labels:
        app: shopnow-frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/shopnow-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://shopnow-backend-service:5000
---
apiVersion: v1
kind: Service
metadata:
  name: shopnow-frontend-service
spec:
  selector:
    app: shopnow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
