replicaCount: 2

frontend:
  image:
    repository: your-dockerhub-user/shopnow-frontend
    tag: latest
  service:
    type: LoadBalancer
    port: 80

backend:
  image:
    repository: your-dockerhub-user/shopnow-backend
    tag: latest
  service:
    type: ClusterIP
    port: 5000

mongodb:
  uri: "mongodb://mongo:27017/shopnow"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: shopnow.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: shopnow-frontend-service
            port: 80
        - path: /api
          pathType: Prefix
          backend:
            service: shopnow-backend-service
            port: 5000
